### ISSUE TITLE
Trouble finding files in windows

### ISSUE THREAD

**Issue by adertobi** [TeaWithLucas/Sort-Photos#10]
Running python3 from Anaconda on win10 machine and I can't get the system to find the files. What can I do?

> (ALR) C:\Sort-Photos-1.2>dir
>
>Volume in drive C is Windows
> Volume Serial Number is xxxxxxxx
>
> Directory of C:\Sort-Photos-1.2
>
>2019-10-25  08:47    <DIR>          .
>2019-10-25  08:47    <DIR>          ..
>2019-10-24  23:19               345 .gitignore
>2019-10-24  23:19           130 555 example.png
>2019-10-24  23:19                24 MANIFEST.in
>2019-10-24  23:19            16 699 README.md
>2019-10-24  23:19               453 setup.py
>2019-10-25  08:47    <DIR>          src
>2019-10-24  23:21    <DIR>          test1
>2019-10-24  23:09    <DIR>          test2
>2019-10-24  23:19               221 TODO.md
>               6 File(s)        148 297 bytes
>               5 Dir(s)  28 929 388 544 bytes free
>
>(ALR) C:\Sort-Photos-1.2>python ./src/sortphotos.py -c ./test1 ./test2
>Hej
>Traceback (most recent call last):
>  File "./src/sortphotos.py", line 611, in <module>
>    main()
>  File "./src/sortphotos.py", line 608, in main
>    sortPhotos(**args)
>  File "./src/sortphotos.py", line 385, in sortPhotos
>    with ExifTool(verbose=verbose) as e:
>  File "./src/sortphotos.py", line 252, in __enter__
>    stdin=subprocess.PIPE, stdout=subprocess.PIPE)
>  File "C:\Users\tobias.aderum\AppData\Local\Continuum\anaconda3\envs\ALR\lib\subprocess.py", >line 775, in __init__
>    restore_signals, start_new_session)
>  File "C:\Users\tobias.aderum\AppData\Local\Continuum\anaconda3\envs\ALR\lib\subprocess.py", >line 1178, in _execute_child
>    startupinfo)
>FileNotFoundError: [WinError 2] The system cannot find the file specified
>
>(ALR) C:\Sort-Photos-1.2>

**Comment by Sillium007** [comment]
@adertobi: it uses Exiftool (https://metacpan.org/pod/Image::ExifTool) which is written in perl. So for sortphotos to work you will also need to install perl
